# Generated by Django 5.2 on 2025-04-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulek')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('main_image', models.ImageField(upload_to='static/articles/main_images/', verbose_name='Titulní fotka')),
                ('content', models.TextField(verbose_name='Obsah')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Datum vytvoření')),
            ],
            options={
                'verbose_name': 'Článek',
                'verbose_name_plural': 'Články',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/articles/additional_images/', verbose_name='Fotka')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dtj_aplikace.article')),
            ],
            options={
                'verbose_name': 'Fotka článku',
                'verbose_name_plural': 'Fotky článku',
            },
        ),
    ]
