# Generated by Django 5.2 on 2025-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0002_event_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název události')),
                ('description', models.TextField(blank=True, verbose_name='Popis události')),
                ('day', models.DateField(verbose_name='Den')),
                ('start_time', models.TimeField(verbose_name='Čas začátku')),
                ('end_time', models.TimeField(verbose_name='Čas konce')),
                ('location', models.CharField(max_length=255, verbose_name='Lokace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Událost',
                'verbose_name_plural': 'Události',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
