# Generated by Django 5.2 on 2025-05-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0003_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Plánn', 'verbose_name_plural': 'Plán'},
        ),
    ]
