# Generated by Django 5.2 on 2025-05-06 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0004_alter_plan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktniZprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('zprava', models.TextField(verbose_name='Zpráva')),
                ('cas_vytvoreni', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Čas vytvoření')),
                ('ip_adresa', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
            ],
            options={
                'verbose_name': 'Kontaktní zpráva',
                'verbose_name_plural': 'Kontaktní zprávy',
            },
        ),
    ]
