# Generated by Django 5.2 on 2025-05-15 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0005_kontaktnizprava'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Plán', 'verbose_name_plural': 'Plán'},
        ),
        migrations.AddField(
            model_name='plan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='plans/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF soubor'),
        ),
    ]
