# Generated by Django 5.2 on 2025-05-15 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0006_alter_plan_options_plan_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/plans/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF soubor'),
        ),
    ]
