# Generated by Django 5.2 on 2025-05-15 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0007_alter_plan_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum vytvoření'),
        ),
    ]
