# Generated by Django 5.2 on 2025-05-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtj_aplikace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulek')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('main_image', models.ImageField(upload_to='static/events/main_images/', verbose_name='Titulní fotka')),
                ('content', models.TextField(verbose_name='Obsah')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Datum vytvoření')),
            ],
            options={
                'verbose_name': 'Akce',
                'verbose_name_plural': 'Akce',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/events/additional_images/', verbose_name='Fotka')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dtj_aplikace.event')),
            ],
            options={
                'verbose_name': 'Fotka akce',
                'verbose_name_plural': 'Fotky akce',
            },
        ),
    ]
